##
## Makefile for Makefile in /home/rosain_f/tmp/PSU_2014_philo/GI
## 
## Made by Francois Rosain
## Login   <rosain_f@epitech.net>
## 
## Started on  Sun Feb 22 17:52:16 2015 Francois Rosain
## Last update Mon Feb 23 15:47:29 2015 Francois Rosain
##

all: 
	$(CC) `pkg-config --cflags --libs gtk+-2.0` *.c -pthread -g3
